### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by jw2476** [Marling-School/marling-game-bot#5]
Add a help command so users can see all available commands, this will need some groundwork to be laid, so all commands have a description

- [x] Covert all commands to objects
- [x] Make a Command interface that all commands will follow
- [x] Write help command which iterates through all registered commands, printing aliases and descriptions

**Comment by jw2476** [comment]
Implemented by #7

**Comment by MarlingSharp** [comment]
Merged in, works well.
